/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analyze/course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** コース（場×距離×馬場）の枠順別統計。 */
        get: operations["analyze_course"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/horse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 馬の成績統計。 */
        get: operations["analyze_horse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/jockey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 騎手の成績統計。 */
        get: operations["analyze_jockey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze/trainer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 調教師の成績統計。 */
        get: operations["analyze_trainer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 指定開催日のライブ EV 買い目（race ごと最新サイクル＋伝票＋フリップ）。
         * @description 該当日の snapshot が無ければ races 空・summary count 0（200 空・404 にしない）。
         */
        get: operations["get_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 予想の横断検索（一覧）。 */
        get: operations["search_predictions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/stats/by-mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 集計の入口（印別の的中率）。 */
        get: operations["prediction_mark_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions/{prediction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 個別予想（ビューア相当・全項目）。 */
        get: operations["get_prediction_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/races": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** レース一覧（指定日）。 */
        get: operations["list_races"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/races/{race_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 出馬表（race card）。 */
        get: operations["get_race_card"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/races/{race_id}/prediction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 確率推定（win/place/show）。 */
        get: operations["get_prediction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/races/{race_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 買い目推奨（軸流しポートフォリオ, EV/推奨額）。保存オッズ基準。
         *     EV・期待回収率は純モデル（市場非依存・α=1.0）× 市場オッズで算出する（#272 循環断ち）。
         *     軸/相手の順位付けは市場ブレンド確率を使う（順位付けと EV で確率系統が異なる）。
         */
        get: operations["get_recommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** セッション収支サマリ + 明細。 */
        get: operations["get_session_summary"];
        put?: never;
        /** セッション新規作成。 */
        post: operations["create_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{date}/races/{race_id}/odds:refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** オッズをライブ取得して保存（#51, read-through）。 */
        post: operations["odds_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{date}/races/{race_id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 1 レース分の賭け金・払戻を記録（残高ガード・1 トランザクション）。 */
        post: operations["record_outcome"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{date}/results:refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 確定結果を取得して払戻を自動補完（#40, 冪等）。 */
        post: operations["results_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description outcome 記録の 1 買い目（リクエスト）。race_id はパスから取るため含めない。 */
        BetInput: {
            /** @description 馬券種ラベル（例 `単勝` / `馬連`）。 */
            bet_type: string;
            /** @description 組み合わせコード（例 `7` / `7-14`）。 */
            combination: string;
            /**
             * Format: double
             * @description 期待値（参考値）。
             */
            ev?: number;
            /**
             * Format: int64
             * @description 払戻（円、記録時点で不明なら 0。results:refresh で確定値に上書きされる）。
             */
            payout?: number;
            /**
             * Format: int64
             * @description 賭け金（円）。
             */
            stake: number;
        };
        /** @description `GET /api/analyze/course?venue=&distance=&surface=` のレスポンス。 */
        CourseStatsResponse: {
            by_gate_group: components["schemas"]["GroupStatSchema"][];
            /** Format: int32 */
            distance: number;
            surface: string;
            venue: string;
        };
        /** @description `POST /api/sessions/{date}` のリクエスト。 */
        CreateSessionRequest: {
            /**
             * Format: int64
             * @description 初期予算（円）。1 以上。
             */
            budget: number;
        };
        /** @description エラーレスポンス本文。`{ "error": { "code": ..., "message": ... } }`。 */
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            /** @description 機械可読なエラーコード（`bad_request` / `not_found` / `conflict` / `internal`）。 */
            code: string;
            /** @description 人間可読なエラーメッセージ。 */
            message: string;
        };
        /** @description あるカテゴリ 1 区分の成績（出走数＋勝/連対/複勝の件数とレート）。 */
        GroupStatSchema: {
            label: string;
            /** Format: double */
            place_rate: number;
            /** Format: int32 */
            places: number;
            /** Format: double */
            show_rate: number;
            /** Format: int32 */
            shows: number;
            /** Format: int32 */
            starts: number;
            /** Format: double */
            win_rate: number;
            /** Format: int32 */
            wins: number;
        };
        /** @description 出馬表の 1 頭。 */
        HorseEntrySchema: {
            /**
             * Format: int32
             * @description 枠番（1..=8）。
             */
            gate_num: number;
            horse_name: string;
            /**
             * Format: int32
             * @description 馬番。
             */
            horse_num: number;
            /** @description 騎手名（PDF 出馬表由来は `null`）。 */
            jockey?: string | null;
            /** @description 調教師名（PDF 出馬表由来は `null`）。 */
            trainer?: string | null;
            /**
             * Format: double
             * @description 負担重量[kg]（PDF 出馬表由来は `null`）。
             */
            weight_carried?: number | null;
        };
        /** @description 1 頭分の win/place/show 確率。 */
        HorseProbabilitySchema: {
            horse_name: string;
            /** Format: int32 */
            horse_num: number;
            /**
             * Format: double
             * @description 連対率（2 着以内）[0,1]。
             */
            place_prob: number;
            /**
             * Format: double
             * @description 複勝率（3 着以内）[0,1]。`win_prob ≤ place_prob ≤ show_prob` を保証。
             */
            show_prob: number;
            /**
             * Format: double
             * @description 勝率 [0,1]。
             */
            win_prob: number;
        };
        /** @description `GET /api/analyze/horse?name=` のレスポンス。 */
        HorseStatsResponse: {
            by_distance_band: components["schemas"]["GroupStatSchema"][];
            by_gate_group: components["schemas"]["GroupStatSchema"][];
            by_popularity_band: components["schemas"]["GroupStatSchema"][];
            by_surface: components["schemas"]["GroupStatSchema"][];
            by_track_condition: components["schemas"]["GroupStatSchema"][];
            horse_name: string;
            overall: components["schemas"]["GroupStatSchema"];
        };
        /** @description `GET /api/analyze/jockey?name=` のレスポンス。 */
        JockeyStatsResponse: {
            by_gate_group: components["schemas"]["GroupStatSchema"][];
            by_surface: components["schemas"]["GroupStatSchema"][];
            jockey_name: string;
            overall: components["schemas"]["GroupStatSchema"];
        };
        /** @description 直前サイクルとの差分（◎変化・+EV↔−EV 反転）。直前が無ければ全て false / null。 */
        LiveFlip: {
            /** @description ◎馬番が直前から変化したか。 */
            axis_changed: boolean;
            /** @description verdict が直前から反転（+EV↔−EV）したか。 */
            ev_reversed: boolean;
            /**
             * Format: int32
             * @description 直前サイクルの◎馬番（無ければ null）。
             */
            prev_axis?: number | null;
            /**
             * Format: double
             * @description 直前サイクルの ROI[%]（無ければ null）。
             */
            prev_roi?: number | null;
            /** @description 直前サイクルの verdict（無ければ null）。 */
            prev_verdict?: string | null;
        };
        /** @description 1 レースの最新サイクル本体＋伝票＋フリップ。 */
        LiveRaceViewSchema: {
            /**
             * Format: int32
             * @description ◎馬番。
             */
            axis: number;
            /**
             * Format: double
             * @description ◎の model 勝率[%]。
             */
            axis_prob: number;
            /**
             * Format: double
             * @description ◎の単勝オッズ（欠落時 null）。
             */
            axis_win_odds?: number | null;
            /** @description 監視サイクル時刻（UTC rfc3339）。 */
            captured_at: string;
            flip: components["schemas"]["LiveFlip"];
            konsen: boolean;
            /** @description 一部買い目のオッズ欠落（ROI 過小評価の可能性）。 */
            odds_missing: boolean;
            /** @description 発走時刻（netkeiba 由来文字列。欠落時 null）。 */
            post_time?: string | null;
            race_id: string;
            /** Format: int32 */
            race_no: number;
            /**
             * Format: double
             * @description 全 3 券種 ROI[%]。
             */
            roi: number;
            slip: components["schemas"]["SlipView"];
            venue: string;
            /** @description `'bet'`（ROI≥100%）/ `'skip'`（−EV）。 */
            verdict: string;
        };
        /**
         * @description `GET /api/live/{date}` のレスポンス（#260 / ADR 0064）。
         *     指定開催日の race ごと最新サイクル＋伝票＋フリップを返す（read-only）。
         */
        LiveResponse: {
            /** @description 開催日（`YYYY-MM-DD`）。 */
            date: string;
            races: components["schemas"]["LiveRaceViewSchema"][];
            summary: components["schemas"]["LiveSummary"];
        };
        /** @description 一望サマリ（張る本数・監視数・最終更新時刻）。 */
        LiveSummary: {
            /**
             * Format: int32
             * @description 最新サイクルが `verdict='bet'` の race 数。
             */
            bet_race_count: number;
            /** @description 全 race 中の最新 `captured_at` の最大値。無ければ null。 */
            last_updated?: string | null;
            /**
             * Format: int32
             * @description 監視レース数（= `races.len()`）。
             */
            watched_race_count: number;
        };
        /** @description 印 1 種の的中率。 */
        MarkStatSchema: {
            /**
             * Format: int32
             * @description その印が付いた（結果記録済みの）馬の延べ数。
             */
            count: number;
            /** @description 印スラッグ（`honmei` 等）。 */
            mark: string;
            /**
             * Format: int32
             * @description 複勝圏（3 着内）に入った延べ数。
             */
            show: number;
            /**
             * Format: double
             * @description 複勝圏到達率（`show / count`。予想入力の `show_prob` とは別概念）。
             */
            show_rate: number;
            /**
             * Format: int32
             * @description 1 着に入った延べ数。
             */
            win: number;
            /**
             * Format: double
             * @description 1 着率（`win / count`）。
             */
            win_rate: number;
        };
        /** @description `GET /api/predictions/stats/by-mark` のレスポンス。 */
        MarkStatsResponse: {
            by_mark: components["schemas"]["MarkStatSchema"][];
        };
        /** @description `POST .../odds:refresh` のレスポンス。 */
        OddsRefreshResponse: {
            /** @description オッズを取得できたか（false = 未公開・取得失敗で未取得。HTTP は 200）。 */
            fetched: boolean;
            race_id: string;
        };
        /** @description `GET /api/predictions/{prediction_id}` のレスポンス（個別予想・全項目）。 */
        PadPredictionResponse: {
            bets: components["schemas"]["PredictionBetSchema"][];
            /** Format: int64 */
            budget?: number | null;
            commentary?: string | null;
            /** Format: date */
            date: string;
            horses: components["schemas"]["PredictionHorseSchema"][];
            /** Format: int64 */
            prediction_id: number;
            /** Format: int32 */
            race_num: number;
            result?: null | components["schemas"]["PredictionResultSchema"];
            strategy_note?: string | null;
            title?: string | null;
            venue: string;
        };
        /** @description 買い目 1 点。 */
        PredictionBetSchema: {
            /** Format: int64 */
            amount: number;
            /** @description 券種（`単勝`/`複勝`/`馬連`/`ワイド`/`馬単`/`3連複`/`3連単`）。 */
            bet_type: string;
            /** @description 組合せ（馬番のハイフン連結。例 `7` / `7-14` / `7-14-13`）。 */
            combination: string;
        };
        /** @description 予想 1 頭分（印・確率・単勝/人気・短評）。 */
        PredictionHorseSchema: {
            comment?: string | null;
            horse_name: string;
            /** Format: int32 */
            horse_num: number;
            jockey?: string | null;
            /** @description 印スラッグ（`honmei`/`taikou`/`tanana`/`renge`/`hoshi`/`chui`）。無印は `null`。 */
            mark?: string | null;
            /** Format: double */
            place_prob?: number | null;
            /** Format: int32 */
            popularity?: number | null;
            /** Format: double */
            show_prob?: number | null;
            /** Format: double */
            win_odds?: number | null;
            /** Format: double */
            win_prob?: number | null;
        };
        /** @description `GET /api/races/{race_id}/prediction` のレスポンス。 */
        PredictionResponse: {
            probabilities: components["schemas"]["HorseProbabilitySchema"][];
            race_id: string;
        };
        /** @description レース結果（答え合わせ後にのみ付く）。 */
        PredictionResultSchema: {
            /** @description `[finish_1, finish_2, finish_3]`（馬番。各要素は `null` 可）。 */
            finish: (number | null)[];
            note?: string | null;
            /** Format: int64 */
            pnl?: number | null;
            /** Format: double */
            recovery_rate?: number | null;
        };
        /** @description `GET /api/predictions` のレスポンス。 */
        PredictionSearchResponse: {
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            predictions: components["schemas"]["PredictionSummarySchema"][];
            /**
             * Format: int64
             * @description フィルタ適用後の総件数（ページング用）。
             */
            total_count: number;
        };
        /** @description 検索一覧の 1 要素（サマリ）。馬・買い目の全量は持たず、個別取得で補う。 */
        PredictionSummarySchema: {
            /** Format: date */
            date: string;
            /**
             * Format: int32
             * @description 距離[m]（`races` 結合で得た値。未照合は `null`）。
             */
            distance?: number | null;
            /** @description `[finish_1, finish_2, finish_3]`（馬番。各要素は `null` 可）。結果未記録なら `null`。 */
            finish?: (number | null)[] | null;
            /** @description 的中。`recovery_rate > 0`→`true`、結果あり且つ払戻 0 以下→`false`、結果未記録→`null`。 */
            hit?: boolean | null;
            /** @description 印 ◎ の馬名（◎が複数なら horse_num 昇順の先頭。無ければ `null`）。 */
            honmei_horse?: string | null;
            /** Format: int64 */
            pnl?: number | null;
            /** Format: int64 */
            prediction_id: number;
            /** @description レース ID（`races`/`race_cards` 照合済みのときのみ。未照合は `null`）。 */
            race_id?: string | null;
            /** Format: int32 */
            race_num: number;
            /** Format: double */
            recovery_rate?: number | null;
            /** @description 芝/ダート（`turf`/`dirt`。未照合は `null`）。 */
            surface?: string | null;
            title?: string | null;
            /** @description 開催場（英字スラッグ。例 `nakayama`）。 */
            venue: string;
        };
        /** @description `GET /api/races/{race_id}` のレスポンス（出馬表）。 */
        RaceCardResponse: {
            /** Format: date */
            date: string;
            /** Format: int32 */
            day: number;
            /** Format: int32 */
            distance: number;
            entries: components["schemas"]["HorseEntrySchema"][];
            race_id: string;
            /** Format: int32 */
            race_num: number;
            /** Format: int32 */
            round: number;
            surface: string;
            venue: string;
        };
        /** @description `GET /api/races?date=` のレスポンス。 */
        RaceListResponse: {
            /** Format: date */
            date: string;
            races: components["schemas"]["RaceSummary"][];
        };
        /** @description レース一覧の 1 要素（出走前の諸元のみ。results は含まない）。 */
        RaceSummary: {
            /**
             * Format: date
             * @description 開催日。
             */
            date: string;
            /**
             * Format: int32
             * @description 距離[m]。
             */
            distance: number;
            /** @description レース ID（`RaceId` の文字列表現）。 */
            race_id: string;
            /**
             * Format: int32
             * @description レース番号（1..=12）。
             */
            race_num: number;
            /** @description 芝/ダート（`turf` / `dirt`）。 */
            surface: string;
            /** @description 開催場（英字スラッグ。例 `nakayama`）。 */
            venue: string;
        };
        /** @description 推奨ポートフォリオ内の 1 買い目。 */
        RecommendationBet: {
            /** @description 券種ラベル（`馬連` / `ワイド` / `三連複`）。 */
            bet_type: string;
            /** @description 組合せキー（馬連・ワイドは `a-b`、三連複は `a-b-c`）。 */
            combination: string;
            /**
             * Format: double
             * @description 期待値倍率（`simulate` 単体評価）。odds 未取得なら 0.0。
             */
            ev: number;
            /**
             * Format: double
             * @description 払戻倍率（保存オッズ未取得の脚は `null`）。ワイドは下限/上限帯の中点。
             */
            odds?: number | null;
            /**
             * Format: int64
             * @description 賭け金（円, 100 円単位）。
             */
            stake: number;
        };
        /**
         * @description `GET /api/races/{race_id}/recommendations` のレスポンス。
         *
         *     CLI `predict` と同じ軸流しポートフォリオ（馬連＋ワイド＋三連複, #122）を予算内・100 円単位で
         *     返す。`bets` が空になる原因は 2 通りで、`odds_available` で区別する:
         *     - `odds_available=false`: 保存オッズ（#51）が無い → SPA は「最新取得」を促す。
         *     - `odds_available=true` かつ `bets` 空: オッズはあるが予算内で組める買い目が無い（または確率が
         *       空）＝「該当なし」→ 「最新取得」は出さない。
         */
        RecommendationResponse: {
            /**
             * Format: int32
             * @description 軸（予想本命）の馬番。確率が空なら `null`。
             */
            axis?: number | null;
            bets: components["schemas"]["RecommendationBet"][];
            /**
             * Format: double
             * @description 同上の的中確率 [0,1]。
             */
            hit_prob?: number | null;
            /** @description 保存オッズ（#51）の有無。false のとき `bets` は必ず空。true でも予算内で組めなければ空になりうる。 */
            odds_available: boolean;
            /** @description 相手（流す先）の馬番。 */
            partners: number[];
            race_id: string;
            /**
             * Format: double
             * @description オッズ取得済みの脚に基づく期待回収率（倍率）。買い目が空なら `null`。
             */
            roi?: number | null;
            /** Format: int64 */
            total_stake: number;
        };
        /** @description `POST /api/sessions/{date}/races/{race_id}/outcome` のリクエスト。 */
        RecordOutcomeRequest: {
            /** @description このレースで購入した買い目（空 = スキップ相当）。 */
            bets: components["schemas"]["BetInput"][];
        };
        /** @description セッション収支サマリ（作成 / outcome / GET summary 共通のレスポンス）。 */
        SessionSummaryResponse: {
            /** Format: int64 */
            balance: number;
            bets: components["schemas"]["SummaryBet"][];
            /** Format: int64 */
            budget: number;
            completed: boolean;
            /** Format: date */
            date: string;
            /**
             * Format: int64
             * @description 損益（`total_payout − total_bet`。負もあるため i64）。
             */
            pnl: number;
            /** Format: int64 */
            total_bet: number;
            /** Format: int64 */
            total_payout: number;
        };
        /** @description `POST .../results:refresh` のレスポンス（`SettleReport` の写像）。 */
        SettleReportResponse: {
            /** Format: int64 */
            balance: number;
            /** Format: int32 */
            pending_races: number;
            /** Format: int32 */
            refunded_bets: number;
            /**
             * Format: double
             * @description 回収率(%)。総賭け金 0 なら null。
             */
            roi?: number | null;
            /** Format: int32 */
            settled_races: number;
            /** Format: int64 */
            total_bet: number;
            /** Format: int64 */
            total_payout: number;
            /** Format: int32 */
            voided_races: number;
        };
        /** @description 伝票の 1 leg（式別×方式×軸×組番×点数×金額の「そのまま買える形」）。 */
        SlipLeg: {
            /**
             * Format: int64
             * @description 金額（100 円単位）。
             */
            amount: number;
            /**
             * Format: int32
             * @description ◎馬番（`method=box` では null）。
             */
            axis?: number | null;
            /** @description 式別（`wide` / `quinella` / `trio`）。 */
            bet_type: string;
            /** @description 組番（昇順ソート済み）。 */
            combo: number[];
            /** @description 方式（`nagashi` / `box` / `formation`）。 */
            method: string;
            /**
             * Format: int32
             * @description この leg の点数。
             */
            points: number;
        };
        /** @description 買い目伝票。`slip` JSONB 列（`{ race_budget, legs }`）をデシリアライズしたもの。 */
        SlipView: {
            /** @description (方式レイヤー × 券種) 単位の leg 配列。 */
            legs: components["schemas"]["SlipLeg"][];
            /**
             * Format: int64
             * @description このレースに配分した予算（円）。
             */
            race_budget: number;
        };
        /** @description サマリの 1 買い目（レスポンス）。どのレースの買い目かを race_id で示す。 */
        SummaryBet: {
            bet_type: string;
            combination: string;
            /** Format: double */
            ev: number;
            /** Format: int64 */
            payout: number;
            race_id: string;
            /** Format: int64 */
            stake: number;
        };
        /** @description `GET /api/analyze/trainer?name=` のレスポンス。 */
        TrainerStatsResponse: {
            by_gate_group: components["schemas"]["GroupStatSchema"][];
            by_surface: components["schemas"]["GroupStatSchema"][];
            overall: components["schemas"]["GroupStatSchema"];
            trainer_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_course: {
        parameters: {
            query: {
                /** @description 開催場（英字スラッグまたは日本語）。 */
                venue: string;
                /** @description 距離[m]。 */
                distance: number;
                /** @description 芝/ダート（`turf` / `dirt`）。 */
                surface: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description コースの枠順別統計 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseStatsResponse"];
                };
            };
            /** @description パラメータ不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    analyze_horse: {
        parameters: {
            query: {
                /** @description 対象の名前（完全一致。あいまい検索は #50）。 */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 馬の成績統計 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HorseStatsResponse"];
                };
            };
            /** @description 名前不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    analyze_jockey: {
        parameters: {
            query: {
                /** @description 対象の名前（完全一致。あいまい検索は #50）。 */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 騎手の成績統計 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JockeyStatsResponse"];
                };
            };
            /** @description 名前不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    analyze_trainer: {
        parameters: {
            query: {
                /** @description 対象の名前（完全一致。あいまい検索は #50）。 */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 調教師の成績統計 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainerStatsResponse"];
                };
            };
            /** @description 名前不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_live: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 開催日 YYYY-MM-DD */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description race ごと最新サイクルの判定＋伝票（無い日は races 空・200） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
            /** @description 日付フォーマット不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー（伝票 JSON 復元失敗を含む） */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    search_predictions: {
        parameters: {
            query?: {
                /** @description 期間開始（`YYYY-MM-DD`。両端含む）。 */
                date_from?: string | null;
                /** @description 期間終了（`YYYY-MM-DD`。両端含む）。 */
                date_to?: string | null;
                /** @description 開催場（英字スラッグまたは日本語）。 */
                venue?: string | null;
                /** @description 距離下限[m]。 */
                distance_min?: number | null;
                /** @description 距離上限[m]。 */
                distance_max?: number | null;
                /** @description 芝/ダート（`turf`/`dirt`）。 */
                surface?: string | null;
                /** @description 馬名の部分一致（カナ正規化される）。 */
                horse_name?: string | null;
                /** @description 印スラッグ（`honmei`/`taikou`/`tanana`/`renge`/`hoshi`/`chui`）。 */
                mark?: string | null;
                /** @description 的中フィルタ（`true`=的中 / `false`=不的中。未指定は全件）。 */
                hit?: boolean | null;
                /** @description 取得件数（既定 50・上限 200）。 */
                limit?: number | null;
                /** @description オフセット（既定 0）。 */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 検索一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionSearchResponse"];
                };
            };
            /** @description クエリ不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    prediction_mark_stats: {
        parameters: {
            query?: {
                /** @description 期間開始（`YYYY-MM-DD`）。 */
                date_from?: string | null;
                /** @description 期間終了（`YYYY-MM-DD`）。 */
                date_to?: string | null;
                /** @description 開催場（英字スラッグまたは日本語）。 */
                venue?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 印別の的中率 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarkStatsResponse"];
                };
            };
            /** @description クエリ不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_prediction_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 予想 ID */
                prediction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 個別予想 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PadPredictionResponse"];
                };
            };
            /** @description 未存在の予想 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_races: {
        parameters: {
            query: {
                /** @description 開催日（`YYYY-MM-DD`）。 */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 指定日のレース一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceListResponse"];
                };
            };
            /** @description 日付フォーマット不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_race_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description レース ID */
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 出馬表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceCardResponse"];
                };
            };
            /** @description レース ID 不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 未存在のレース */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_prediction: {
        parameters: {
            query?: {
                /** @description 馬場状態（`良` / `稍重` / `重` / `不良`。略記 `稍` / `不` も可）。未指定なら馬場項なし。 */
                track_condition?: string | null;
                /** @description 市場オッズ（単勝）とのブレンド係数 `[0,1]`。未指定は本番ブレンド α=0.2。素モデルは `1.0` を明示。 */
                blend_alpha?: number | null;
            };
            header?: never;
            path: {
                /** @description レース ID */
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 馬ごとの確率 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description クエリ不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 出馬表が無いレース */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_recommendations: {
        parameters: {
            query: {
                /** @description このレースに配分する予算（円）。1 以上。100 円単位の買い目に配分される。 */
                budget: number;
                /** @description 馬場状態（`良` / `稍重` / `重` / `不良`。略記 `稍` / `不` も可）。未指定なら馬場項なし。 */
                track_condition?: string | null;
                /** @description 市場オッズ（単勝）とのブレンド係数 `[0,1]`。未指定は本番ブレンド α=0.2。素モデルは `1.0` を明示（`/prediction` と同義）。 */
                blend_alpha?: number | null;
            };
            header?: never;
            path: {
                /** @description レース ID */
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 予算内の軸流しポートフォリオ（EV は純モデル×市場オッズ。オッズ未保存なら odds_available=false） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description クエリ不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 出馬表が無いレース */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_session_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 開催日 YYYY-MM-DD */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description セッション収支 + 明細 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryResponse"];
                };
            };
            /** @description 日付不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 未作成のセッション */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 開催日 YYYY-MM-DD */
                date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description 作成したセッションのサマリ */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryResponse"];
                };
            };
            /** @description budget 不正・日付不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 同一開催日のセッションが既に存在 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    odds_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 開催日 YYYY-MM-DD */
                date: string;
                /** @description レース ID */
                race_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得結果（未取得は fetched=false・HTTP は 200） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OddsRefreshResponse"];
                };
            };
            /** @description 日付/ID 不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 未作成のセッション */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    record_outcome: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 開催日 YYYY-MM-DD */
                date: string;
                /** @description レース ID */
                race_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordOutcomeRequest"];
            };
        };
        responses: {
            /** @description 更新後のセッションサマリ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryResponse"];
                };
            };
            /** @description 残高超過・日付/ID 不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 未作成のセッション */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 当該レースの outcome が既に記録済み */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    results_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 開催日 YYYY-MM-DD */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 精算レポート（pending_races に未確定が出る） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettleReportResponse"];
                };
            };
            /** @description 日付不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 未作成のセッション */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description 内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
