#!/usr/bin/env bash
# scripts/check-vendored-swagger.sh の回帰テスト（ADR 0082）。
#
# **なぜ検査にテストが要るか**: リポジトリは常に合格側なので、検査が壊れても本番データが正常だと
# 無言で緑になる。ADR 0073 が `adr` ジョブを「回帰テスト → 本番検査」の順にしたのと同じ理由で、
# fail-closed を謳う検査ほど自身の回帰を持つ必要がある。
#
# 一時ディレクトリに最小の Cargo.toml / Cargo.lock を作り、検査対象スクリプトをそこで走らせる
# （スクリプトは `git rev-parse --show-toplevel` で基準を取るので git init も行う）。
set -euo pipefail

# git hook から呼ばれると GIT_DIR / GIT_WORK_TREE が環境に入り、下で作る一時リポジトリ内の
# git が**本物のリポジトリを指す**（#645）。本テストは現状 `git -C` 併用で通っているが、
# `git rev-parse --show-toplevel` を使う検査対象を temp repo で走らせる構造は同じ罠を抱えるので、
# 予防的に落とす。
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE

TARGET=$(cd "$(dirname "$0")" && pwd)/check-vendored-swagger.sh
pass=0
fail=0

make_repo() {
    # $1 = Cargo.toml の中身 / $2 = Cargo.lock の中身
    local dir
    dir=$(mktemp -d)
    git -C "$dir" init -q
    printf '%s' "$1" > "$dir/Cargo.toml"
    printf '%s' "$2" > "$dir/Cargo.lock"
    echo "$dir"
}

LOCK_OK='# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "utoipa-swagger-ui"
version = "9.0.2"

[[package]]
name = "utoipa-swagger-ui-vendored"
version = "0.1.2"
'

LOCK_MISSING='# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "utoipa-swagger-ui"
version = "9.0.2"
'

# [[package]] ではないセクションに name 行がある形（誤一致の確認）
LOCK_WRONG_SECTION='# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "utoipa-swagger-ui"
version = "9.0.2"

[[patch.unused]]
name = "utoipa-swagger-ui-vendored"
version = "0.1.2"
'

check() {
    # $1 = ケース名 / $2 = 期待（pass|fail）/ $3 = Cargo.toml / $4 = Cargo.lock
    local name="$1" expect="$2" dir code
    dir=$(make_repo "$3" "$4")
    set +e
    (cd "$dir" && bash "$TARGET" >/dev/null 2>&1)
    code=$?
    set -e
    rm -rf "$dir"
    if { [ "$expect" = "pass" ] && [ "$code" -eq 0 ]; } \
        || { [ "$expect" = "fail" ] && [ "$code" -ne 0 ]; }; then
        echo "  ✓ $name"
        pass=$((pass + 1))
    else
        echo "  ✗ ${name}（期待 ${expect} / exit ${code}）" >&2
        fail=$((fail + 1))
    fi
}

echo "check-vendored-swagger.sh 回帰テスト"

check "vendored あり（1 行）" pass \
    'utoipa-swagger-ui = { version = "9", features = ["actix-web", "vendored"] }
' "$LOCK_OK"

check "vendored あり（features を複数行に整形）" pass \
    'utoipa-swagger-ui = { version = "9", features = [
    "actix-web",
    "vendored",
] }
' "$LOCK_OK"

check "vendored が落ちた" fail \
    'utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
' "$LOCK_OK"

# 行末コメントにだけ "vendored" があるケース。features 配列の中だけを見ないと通ってしまう（偽陰性）。
check "行末コメントにだけ vendored がある" fail \
    'utoipa-swagger-ui = { version = "9", features = ["actix-web"] } # "vendored" は 0.2 で改名予定
' "$LOCK_OK"

check "Cargo.lock から vendored が消えた" fail \
    'utoipa-swagger-ui = { version = "9", features = ["actix-web", "vendored"] }
' "$LOCK_MISSING"

# [[patch.unused]] の name 行に誤一致すると、解決されていないのに通ってしまう。
check "Cargo.lock の [[package]] 以外に name 行がある" fail \
    'utoipa-swagger-ui = { version = "9", features = ["actix-web", "vendored"] }
' "$LOCK_WRONG_SECTION"

check "宣言そのものが無い" fail \
    'utoipa = { version = "5" }
' "$LOCK_OK"

# crate 名の前方一致で別 crate を拾わないこと。
check "似た名前の別 crate にだけ vendored がある" fail \
    'utoipa-swagger-ui-x = { version = "9", features = ["vendored"] }
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
' "$LOCK_OK"

echo
if [ "$fail" -ne 0 ]; then
    echo "✗ $fail / $((pass + fail)) 件が失敗した" >&2
    exit 1
fi
echo "✓ 全 $pass ケース通過"
