-- Postgres ベースライン（SQLite からの移行で、旧 50 マイグレーションを最終形に集約）。
-- 整数列は DTO の i64 マッピングを保つため BIGINT、小数は DOUBLE PRECISION。
-- AUTOINCREMENT は GENERATED BY DEFAULT AS IDENTITY（pgloader が既存 id を明示挿入できる）。
-- 日付は SQLite と同じく TEXT（YYYY-MM-DD）。

CREATE TABLE races (
    race_id          TEXT PRIMARY KEY,
    date             TEXT NOT NULL,
    venue            TEXT NOT NULL,
    round            BIGINT NOT NULL,
    day              BIGINT NOT NULL,
    race_num         BIGINT NOT NULL,
    surface          TEXT NOT NULL,
    distance         BIGINT NOT NULL,
    track_condition  TEXT,
    weather          TEXT,
    source           TEXT NOT NULL DEFAULT 'pdf'
);
CREATE INDEX idx_races_course ON races(venue, distance, surface);
CREATE INDEX idx_races_condition ON races(track_condition);

CREATE TABLE results (
    result_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id             TEXT NOT NULL REFERENCES races(race_id) ON DELETE CASCADE,
    finishing_position  BIGINT,
    gate_num            BIGINT NOT NULL,
    horse_num           BIGINT NOT NULL,
    horse_name          TEXT NOT NULL,
    jockey              TEXT,
    trainer             TEXT,
    time_seconds        DOUBLE PRECISION,
    margin              TEXT,
    odds                DOUBLE PRECISION,
    horse_weight        BIGINT,
    weight_change       BIGINT,
    weight_carried      DOUBLE PRECISION,
    popularity          BIGINT,
    status              TEXT NOT NULL DEFAULT 'finished',
    source              TEXT NOT NULL DEFAULT 'pdf',
    horse_id            TEXT,
    UNIQUE(race_id, horse_num)
);
CREATE INDEX idx_results_horse     ON results(horse_name);
CREATE INDEX idx_results_jockey    ON results(jockey);
CREATE INDEX idx_results_gate      ON results(gate_num);
CREATE INDEX idx_results_horse_id  ON results(horse_id);
CREATE INDEX idx_results_trainer   ON results(trainer) WHERE trainer IS NOT NULL;

CREATE TABLE fetch_history (
    source_key   TEXT PRIMARY KEY,
    url          TEXT NOT NULL,
    races_saved  BIGINT NOT NULL DEFAULT 0,
    horses_saved BIGINT NOT NULL DEFAULT 0,
    fetched_at   TEXT NOT NULL
);

CREATE TABLE race_cards (
    race_id   TEXT PRIMARY KEY,
    venue     TEXT NOT NULL,
    round     BIGINT NOT NULL,
    day       BIGINT NOT NULL,
    race_num  BIGINT NOT NULL,
    surface   TEXT NOT NULL,
    distance  BIGINT NOT NULL,
    date      TEXT
);
CREATE INDEX idx_race_cards_date ON race_cards(date);

CREATE TABLE horse_entries (
    entry_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id    TEXT NOT NULL REFERENCES race_cards(race_id) ON DELETE CASCADE,
    gate_num   BIGINT NOT NULL,
    horse_num  BIGINT NOT NULL,
    horse_name TEXT NOT NULL,
    jockey     TEXT,
    trainer    TEXT,
    weight_carried DOUBLE PRECISION,
    UNIQUE(race_id, horse_num)
);
CREATE INDEX idx_horse_entries_race_id    ON horse_entries(race_id);
CREATE INDEX idx_horse_entries_horse_name ON horse_entries(horse_name);

CREATE TABLE predict_sessions (
    date         TEXT PRIMARY KEY,           -- YYYY-MM-DD
    budget       BIGINT NOT NULL,            -- 開始予算（円）
    balance      BIGINT NOT NULL,            -- 現在残高（円）
    total_bet    BIGINT NOT NULL DEFAULT 0,
    total_payout BIGINT NOT NULL DEFAULT 0,
    completed    BIGINT NOT NULL DEFAULT 0,  -- 0/1: 全レース処理済みか
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL
);

CREATE TABLE predict_bets (
    bet_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_date TEXT NOT NULL REFERENCES predict_sessions(date) ON DELETE CASCADE,
    race_id      TEXT NOT NULL,
    bet_type     TEXT NOT NULL,              -- win/place/quinella/exacta/trio/trifecta
    combination  TEXT NOT NULL,              -- "3" / "1-5" / "1>5" / "1-3-5" / "1>3>5"
    stake        BIGINT NOT NULL,            -- 賭け金（円）
    payout       BIGINT NOT NULL DEFAULT 0,  -- 払戻（円, per-bet）
    ev           DOUBLE PRECISION NOT NULL,
    created_at   TEXT NOT NULL
);
CREATE INDEX idx_predict_bets_race ON predict_bets(session_date, race_id);

CREATE TABLE race_odds (
    race_id         TEXT NOT NULL,
    bet_type        TEXT NOT NULL,
    combination_key TEXT NOT NULL,
    odds            DOUBLE PRECISION NOT NULL,
    odds_high       DOUBLE PRECISION,
    popularity      BIGINT,
    fetched_at      TEXT NOT NULL,
    PRIMARY KEY (race_id, bet_type, combination_key)
);

CREATE TABLE horses (
    horse_id    TEXT PRIMARY KEY,
    horse_name  TEXT NOT NULL
);
CREATE INDEX idx_horses_name ON horses(horse_name);

CREATE TABLE horse_past_runs (
    horse_id            TEXT NOT NULL REFERENCES horses(horse_id) ON DELETE CASCADE,
    race_id             TEXT NOT NULL,
    netkeiba_race_id    TEXT NOT NULL,
    date                TEXT NOT NULL,
    venue               TEXT NOT NULL,
    round               BIGINT NOT NULL,
    day                 BIGINT NOT NULL,
    race_num            BIGINT NOT NULL,
    surface             TEXT NOT NULL,
    distance            BIGINT NOT NULL,
    track_condition     TEXT,
    finishing_position  BIGINT,
    status              TEXT NOT NULL,
    gate_num            BIGINT NOT NULL,
    horse_num           BIGINT NOT NULL,
    horse_name          TEXT NOT NULL,
    jockey              TEXT,
    time_seconds        DOUBLE PRECISION,
    margin              TEXT,
    odds                DOUBLE PRECISION,
    horse_weight        BIGINT,
    weight_change       BIGINT,
    weight_carried      DOUBLE PRECISION,
    popularity          BIGINT,
    PRIMARY KEY (horse_id, race_id)
);
CREATE INDEX idx_horse_past_runs_name ON horse_past_runs(horse_name);
CREATE INDEX idx_horse_past_runs_date ON horse_past_runs(date);

CREATE TABLE predict_race_conditions (
    session_date    TEXT NOT NULL REFERENCES predict_sessions(date) ON DELETE CASCADE,
    race_id         TEXT NOT NULL,
    track_condition TEXT,                       -- 良/稍重/重/不良。NULL=不明として記録
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    PRIMARY KEY (session_date, race_id)
);

CREATE TABLE predictions (
    prediction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date          TEXT NOT NULL,              -- YYYY-MM-DD
    venue         TEXT NOT NULL,              -- 日本語の場名（races.venue と同形式）
    race_num      BIGINT NOT NULL,
    race_id       TEXT,                       -- races 照合で解決できた時のみ
    title         TEXT,                       -- H1 のレース名/クラス
    budget        BIGINT,                     -- 予算（円）
    strategy_note TEXT,                       -- 買い目の狙い/方針
    commentary    TEXT,                       -- 敗因分析等の自由記述（生成 MD 末尾に出す）
    finish_1      BIGINT,                     -- 結果 1 着（馬番）
    finish_2      BIGINT,                     -- 結果 2 着（馬番）
    finish_3      BIGINT,                     -- 結果 3 着（馬番）
    recovery_rate DOUBLE PRECISION,           -- 回収率（%）
    pnl           BIGINT,                     -- 収支（円, 符号付き）
    result_note   TEXT,                       -- 結果コメント（自由記述）
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    UNIQUE(date, venue, race_num)
);

CREATE TABLE prediction_horses (
    prediction_id BIGINT NOT NULL REFERENCES predictions(prediction_id) ON DELETE CASCADE,
    horse_num     BIGINT NOT NULL,
    horse_name    TEXT NOT NULL,
    jockey        TEXT,
    mark          TEXT,                       -- honmei/taikou/tanana/renge/hoshi/chui
    win_odds      DOUBLE PRECISION,           -- 単勝オッズ
    popularity    BIGINT,                     -- 人気
    win_prob      DOUBLE PRECISION,           -- 勝率
    place_prob    DOUBLE PRECISION,           -- 連対率
    show_prob     DOUBLE PRECISION,           -- 複勝率
    comment       TEXT,                       -- 短評
    PRIMARY KEY (prediction_id, horse_num)
);
CREATE INDEX idx_prediction_horses_name ON prediction_horses(horse_name);
CREATE INDEX idx_prediction_horses_mark ON prediction_horses(mark);

CREATE TABLE prediction_bets (
    prediction_id BIGINT NOT NULL REFERENCES predictions(prediction_id) ON DELETE CASCADE,
    ordinal       BIGINT NOT NULL,
    bet_type      TEXT NOT NULL,              -- 単勝/複勝/馬連/ワイド/馬単/3連複/3連単
    combination   TEXT NOT NULL,              -- "7" / "7-14" / "7-14-13"
    amount        BIGINT NOT NULL,            -- 金額（円）
    PRIMARY KEY (prediction_id, ordinal)
);
